/*Bank Actions*/
const DEPOSIT_MONEY = "DEPOSIT_MONEY"
const WITHDRAW_MONEY = "WITHDRAW_MONEY"
const RESET_ACOUNT = "RESET_ACOUNT"
export{
    DEPOSIT_MONEY,
    WITHDRAW_MONEY,
    RESET_ACOUNT
}

/*Quotes Actions*/
const SAVE_QUOTE = "SAVE_QUOTE"
const SAVING_QUOTE = "SAVING_QUOTE"
const SAVED_QUOTE = "SAVED_QUOTE"
const SAVE_QUOTE_ERROR = "SAVE_QUOTE_ERROR"

export{
    SAVE_QUOTE,
    SAVING_QUOTE,
    SAVED_QUOTE,
    SAVE_QUOTE_ERROR
}

/*POKEMON Actions*/
const GET_POKEMON = "GET_POKEMON"
const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS"
const GET_POKEMON_ERROR = "GET_POKEMON_ERROR"

export{
    GET_POKEMON,
    GET_POKEMON_SUCCESS,
    GET_POKEMON_ERROR
}